name: Bing Wallpaper Build And Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:  
  schedule:
    - cron: "00 16 * * *"  
env:
  TZ: Asia/Shanghai
jobs:
  build-project:
    name: Bing Wallpaper Build And Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: set Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: install deploy
        run:  pnpm install

      - name: build project
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |
          pnpm run build || pnpm run docs:build

      - name: Check if there are any changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT 
          
      - name: Deploy to hefung/docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./.vitepress/dist
          token: ${{ secrets.PUBLISH_DOCS }}
          single-commit: true  
      
      - name: æäº¤é¡¹ç›® ğŸ±â€ğŸ
        if: steps.verify_diff.outputs.changed == 'true'
        run: | 
          git config --local user.email "28900094+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "update bing viptv dev project"

      - name: æ‹‰å–å˜æ›´ ğŸš€
        if: steps.verify_diff.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUBLISH_DOCS }}
          branch: main     
